### ISSUE TITLE
PHP 8.0 (en hoger) ondersteuning ontbreekt

### ISSUE THREAD

**Issue by dennisb1** [myparcelnl/opencart3#15]
Plugin werkt dan niet, je krijgt CURL errors op het moment dat je labels wil genereren.

Wordt deze plugin überhaupt nog onderhouden?

**Comment by gsaftw** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=f072322672648a249f8744ed15dbfbcc&extension_id=45817

hier werkend script bij mij iig, 

heb ze al de bron gegeven

**Comment by dennisb1** [comment]
@gsaftw Ik kan inderdaad bevestigen dat dit volledig lijkt te werken zonder iets wat omvalt met PHP 8.2.15

**Comment by gsaftw** [comment]
zet ik dat even in de extensie erbij dat hoger ook werkt, bedankt voor de info @dennisb1

**Comment by dennisb1** [comment]
Wel, er blijkt nog een addertje onder het gras te zitten.
In de errorlog komt dit duizenden keren voor, wel is het zo dat dit geen invloed aan de beheer/gebruikerskant heeft.

`2024-03-10 18:15:54 - PHP Unknown:  Creation of dynamic property MyParcel::$shipment is deprecated in /home/*****/domains/*****/public_html/system/library/myparcelnl/class_myparcel.php on line 42
2024-03-10 18:15:54 - PHP Unknown:  Creation of dynamic property MyParcel::$url is deprecated in /home/*****/domains/*****/public_html/system/library/myparcelnl/class_myparcel.php on line 50`
